services:
  db-dev:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discussion-forum
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: discussion-forum-dev