/*
 * This file is generated by jOOQ.
 */
package com.devacademy.discussionforum.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String username;
    private String passwordHash;
    private Boolean isAdmin;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.username = value.username;
        this.passwordHash = value.passwordHash;
        this.isAdmin = value.isAdmin;
    }

    public Users(
        Integer id,
        String username,
        String passwordHash,
        Boolean isAdmin
    ) {
        this.id = id;
        this.username = username;
        this.passwordHash = passwordHash;
        this.isAdmin = isAdmin;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.users.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.users.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>public.users.password_hash</code>.
     */
    public String getPasswordHash() {
        return this.passwordHash;
    }

    /**
     * Setter for <code>public.users.password_hash</code>.
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * Getter for <code>public.users.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    /**
     * Setter for <code>public.users.is_admin</code>.
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.passwordHash == null) {
            if (other.passwordHash != null)
                return false;
        }
        else if (!this.passwordHash.equals(other.passwordHash))
            return false;
        if (this.isAdmin == null) {
            if (other.isAdmin != null)
                return false;
        }
        else if (!this.isAdmin.equals(other.isAdmin))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.passwordHash == null) ? 0 : this.passwordHash.hashCode());
        result = prime * result + ((this.isAdmin == null) ? 0 : this.isAdmin.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(isAdmin);

        sb.append(")");
        return sb.toString();
    }
}
