/*
 * This file is generated by jOOQ.
 */
package com.devacademy.discussionforum.jooq;


import com.devacademy.discussionforum.jooq.tables.ForumUser;
import com.devacademy.discussionforum.jooq.tables.Message;
import com.devacademy.discussionforum.jooq.tables.Topic;
import com.devacademy.discussionforum.jooq.tables.records.ForumUserRecord;
import com.devacademy.discussionforum.jooq.tables.records.MessageRecord;
import com.devacademy.discussionforum.jooq.tables.records.TopicRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ForumUserRecord> FORUM_USER_PKEY = Internal.createUniqueKey(ForumUser.FORUM_USER, DSL.name("forum_user_pkey"), new TableField[] { ForumUser.FORUM_USER.ID }, true);
    public static final UniqueKey<ForumUserRecord> FORUM_USER_USERNAME_KEY = Internal.createUniqueKey(ForumUser.FORUM_USER, DSL.name("forum_user_username_key"), new TableField[] { ForumUser.FORUM_USER.USERNAME }, true);
    public static final UniqueKey<MessageRecord> MESSAGE_PKEY = Internal.createUniqueKey(Message.MESSAGE, DSL.name("message_pkey"), new TableField[] { Message.MESSAGE.ID }, true);
    public static final UniqueKey<TopicRecord> TOPIC_PKEY = Internal.createUniqueKey(Topic.TOPIC, DSL.name("topic_pkey"), new TableField[] { Topic.TOPIC.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MessageRecord, TopicRecord> MESSAGE__MESSAGE_TOPIC_ID_FKEY = Internal.createForeignKey(Message.MESSAGE, DSL.name("message_topic_id_fkey"), new TableField[] { Message.MESSAGE.TOPIC_ID }, Keys.TOPIC_PKEY, new TableField[] { Topic.TOPIC.ID }, true);
    public static final ForeignKey<MessageRecord, ForumUserRecord> MESSAGE__MESSAGE_USER_ID_FKEY = Internal.createForeignKey(Message.MESSAGE, DSL.name("message_user_id_fkey"), new TableField[] { Message.MESSAGE.USER_ID }, Keys.FORUM_USER_PKEY, new TableField[] { ForumUser.FORUM_USER.ID }, true);
    public static final ForeignKey<TopicRecord, ForumUserRecord> TOPIC__TOPIC_USER_ID_FKEY = Internal.createForeignKey(Topic.TOPIC, DSL.name("topic_user_id_fkey"), new TableField[] { Topic.TOPIC.USER_ID }, Keys.FORUM_USER_PKEY, new TableField[] { ForumUser.FORUM_USER.ID }, true);
}
