/*
 * This file is generated by jOOQ.
 */
package com.devacademy.discussionforum.jooq;


import com.devacademy.discussionforum.jooq.tables.Messages;
import com.devacademy.discussionforum.jooq.tables.Topics;
import com.devacademy.discussionforum.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.topics</code>.
     */
    public static final Topics TOPICS = Topics.TOPICS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
