/*
 * This file is generated by jOOQ.
 */
package com.devacademy.discussionforum.jooq;


import com.devacademy.discussionforum.jooq.tables.ForumUser;
import com.devacademy.discussionforum.jooq.tables.Message;
import com.devacademy.discussionforum.jooq.tables.Topic;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.forum_user</code>.
     */
    public static final ForumUser FORUM_USER = ForumUser.FORUM_USER;

    /**
     * The table <code>public.message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>public.topic</code>.
     */
    public static final Topic TOPIC = Topic.TOPIC;
}
