/*
 * This file is generated by jOOQ.
 */
package com.devacademy.discussionforum.jooq.tables.records;


import com.devacademy.discussionforum.jooq.tables.ForumUser;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ForumUserRecord extends UpdatableRecordImpl<ForumUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.forum_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.forum_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.forum_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.forum_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.forum_user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.forum_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.forum_user.is_admin</code>.
     */
    public void setIsAdmin(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.forum_user.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ForumUserRecord
     */
    public ForumUserRecord() {
        super(ForumUser.FORUM_USER);
    }

    /**
     * Create a detached, initialised ForumUserRecord
     */
    public ForumUserRecord(Integer id, String username, String passwordHash, Boolean isAdmin) {
        super(ForumUser.FORUM_USER);

        setId(id);
        setUsername(username);
        setPasswordHash(passwordHash);
        setIsAdmin(isAdmin);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ForumUserRecord
     */
    public ForumUserRecord(com.devacademy.discussionforum.jooq.tables.pojos.ForumUser value) {
        super(ForumUser.FORUM_USER);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setPasswordHash(value.getPasswordHash());
            setIsAdmin(value.getIsAdmin());
            resetChangedOnNotNull();
        }
    }
}
