/*
 * This file is generated by jOOQ.
 */
package com.devacademy.discussionforum.jooq.tables.records;


import com.devacademy.discussionforum.jooq.tables.Message;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.message.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.message.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.message.topic_id</code>.
     */
    public void setTopicId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.message.topic_id</code>.
     */
    public Integer getTopicId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.message.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.message.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.message.up_votes</code>.
     */
    public void setUpVotes(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.message.up_votes</code>.
     */
    public Integer getUpVotes() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.message.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.message.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.message.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.message.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Integer id, Integer userId, Integer topicId, String message, Integer upVotes, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Message.MESSAGE);

        setId(id);
        setUserId(userId);
        setTopicId(topicId);
        setMessage(message);
        setUpVotes(upVotes);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(com.devacademy.discussionforum.jooq.tables.pojos.Message value) {
        super(Message.MESSAGE);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setTopicId(value.getTopicId());
            setMessage(value.getMessage());
            setUpVotes(value.getUpVotes());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
